baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '新闻网'
theme = 'ananke'
hasCJKLanguage = true
summaryLength = 16
publishDir = "docs"




[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

