baseURL = 'https://wt-88.github.io/newsite/'
languageCode = 'en-us'
publishDir = "docs"
title = '新闻网'
theme = 'ananke'
hasCJKLanguage = true
summaryLength = 16

canonifyurls = true




[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

